#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Gera todos os arquivos da skill markdown-fundamentals e conta linhas.
"""
import os

TB = '`' * 3   # triple backtick
TB4 = '`' * 4  # quadruple backtick

# ============================================================
# SKILL.md
# ============================================================
SKILL_MD = (
    "---\n"
    "name: markdown-fundamentals\n"
    "description: |\n"
    "  Guia completo para criação de documentos Markdown seguindo boas práticas,\n"
    "  sintaxe CommonMark e extensões populares (GFM, tabelas, diagramas Mermaid).\n"
    "  Use quando: criar ou revisar arquivos .md, escrever documentação técnica,\n"
    "  garantir compatibilidade entre GitHub, GitLab e sites de docs.\n"
    "license: MIT\n"
    "metadata: ./metadata.yaml\n"
    "---\n"
    "\n"
    "# Markdown Fundamentals\n"
    "\n"
    "Skill para criação e manutenção de documentos Markdown seguindo especificações CommonMark, extensões GFM e boas práticas de compatibilidade entre plataformas. Cobre desde sintaxe básica até recursos avançados como tabelas, blocos de código, diagramas e seções colapsáveis, sem dependência de framework específico.\n"
    "\n"
    "---\n"
    "\n"
    "## When to Use\n"
    "\n"
    "Use esta skill quando precisar:\n"
    "\n"
    "- **Criar ou revisar documentação técnica** (READMEs, guias, wikis)\n"
    "- **Escrever arquivos Markdown para repositórios** no GitHub, GitLab ou Bitbucket\n"
    "- **Estruturar documentos com hierarquia de headings** clara e acessível\n"
    "- **Usar tabelas, listas e blocos de código** formatados corretamente\n"
    "- **Adicionar diagramas** via Mermaid em documentação\n"
    "- **Garantir compatibilidade** entre diferentes renderizadores Markdown\n"
    "- **Aplicar badges, links relativos e imagens** em documentação\n"
    "- **Usar front matter YAML** em arquivos Markdown para metadados\n"
    "\n"
    "**Não use para:** Criação de sites completos (Jekyll, Hugo), slides de apresentação, edição de formatos proprietários (Confluence XHTML, Word).\n"
    "\n"
    "---\n"
    "\n"
    "## Instructions\n"
    "\n"
    "### Step 1: Analisar Contexto\n"
    "\n"
    "Antes de criar ou revisar um documento Markdown, identifique:\n"
    "\n"
    "1. **Plataforma de destino**\n"
    "   - GitHub, GitLab, Bitbucket → suportam GFM com variações específicas\n"
    "   - Sites de docs (MkDocs, Docusaurus, Hugo) → suportam extensões extras\n"
    "   - Visualizador genérico → aderir ao CommonMark estrito\n"
    "\n"
    "2. **Propósito do documento**\n"
    "   - README de repositório → conciso, com badges e links de navegação\n"
    "   - Documentação de API → estrutura detalhada, exemplos de código\n"
    "   - Wiki interna → hierarquia profunda, cross-links entre páginas\n"
    "\n"
    "3. **Convenções existentes no projeto**\n"
    "   - Estilo de indentação (2 ou 4 espaços para listas aninhadas)\n"
    "   - Uso de `---` vs `***` para quebras horizontais\n"
    "   - Padrão de links (inline vs estilo referência)\n"
    "\n"
    "### Step 2: Aplicar Estrutura Base\n"
    "\n"
    "**Hierarquia de headings (H1\u2013H6):**\n"
    + TB + "markdown\n"
    "# Título Principal (H1) \u2014 apenas um por documento\n"
    "\n"
    "## Seção Principal (H2)\n"
    "\n"
    "### Subseção (H3)\n"
    "\n"
    "#### Detalhe (H4) \u2014 usar com moderação\n"
    + TB + "\n"
    "\n"
    "**Ênfase e formatação inline:**\n"
    + TB + "markdown\n"
    "**texto em negrito**\n"
    "*texto em itálico*\n"
    "***texto negrito e itálico***\n"
    "~~texto riscado~~          <!-- GFM apenas -->\n"
    "`código inline`\n"
    + TB + "\n"
    "\n"
    "**Listas básicas:**\n"
    + TB + "markdown\n"
    "- Item não ordenado\n"
    "- Outro item\n"
    "  - Sub-item (indentado com 2 espaços)\n"
    "\n"
    "1. Item ordenado\n"
    "2. Segundo item\n"
    "   1. Sub-item ordenado\n"
    + TB + "\n"
    "\n"
    "**Links e quebra de linha:**\n"
    + TB + "markdown\n"
    "[texto do link](https://exemplo.com)\n"
    '[link com título](https://exemplo.com "Título ao hover")\n'
    "\n"
    "Duas barras finais para quebra de linha  \n"
    "ou uma linha em branco entre parágrafos.\n"
    + TB + "\n"
    "\n"
    "### Step 3: Usar Recursos Avançados\n"
    "\n"
    "**Blocos de código com realce de sintaxe:**\n"
    + TB4 + "markdown\n"
    + TB + "python\n"
    'def saudacao(nome: str) -> str:\n'
    '    return f"Olá, {nome}!"\n'
    + TB + "\n"
    + TB4 + "\n"
    "\n"
    "**Tabelas (GFM):**\n"
    + TB + "markdown\n"
    "| Coluna A | Coluna B | Coluna C |\n"
    "|----------|:--------:|---------:|\n"
    "| esquerda | centro   |  direita |\n"
    + TB + "\n"
    "\n"
    "**Blocos de citação:**\n"
    + TB + "markdown\n"
    "> Citação principal\n"
    ">\n"
    "> > Citação aninhada (dois níveis)\n"
    + TB + "\n"
    "\n"
    "**Diagramas Mermaid (GitHub, GitLab, MkDocs):**\n"
    + TB4 + "markdown\n"
    + TB + "mermaid\n"
    "graph TD\n"
    "    A[Início] --> B{Decisão}\n"
    "    B -->|Sim| C[Resultado A]\n"
    "    B -->|Não| D[Resultado B]\n"
    + TB + "\n"
    + TB4 + "\n"
    "\n"
    "**Seção colapsável (HTML em Markdown):**\n"
    + TB + "markdown\n"
    "<details>\n"
    "<summary>Clique para expandir</summary>\n"
    "\n"
    "Conteúdo oculto por padrão.\n"
    "\n"
    "</details>\n"
    + TB + "\n"
    "\n"
    "### Step 4: Validar e Revisar\n"
    "\n"
    "**Checklist Final:**\n"
    "- [ ] Apenas um H1 no documento\n"
    "- [ ] Hierarquia de headings sem saltos (H1 \u2192 H2 \u2192 H3, nunca H1 \u2192 H3)\n"
    "- [ ] Todos os links funcionam (relativos e externos verificados)\n"
    "- [ ] Blocos de código com linguagem especificada após as marcas cercadas\n"
    "- [ ] Tabelas com alinhamento consistente e cabeçalho separador presente\n"
    "- [ ] Sem caracteres especiais não escapados que quebrem a renderização\n"
    "- [ ] Front matter YAML válido quando utilizado\n"
    "- [ ] Compatível com a plataforma de destino (consulte compatibility.md)\n"
    "\n"
    "---\n"
    "\n"
    "## Referências JIT\n"
    "\n"
    "Para tópicos avançados, consulte as referências detalhadas:\n"
    "\n"
    "| Tópico | Arquivo | Conteúdo |\n"
    "|--------|---------|----------|\n"
    "| Hierarquia de Headings | [headings-structure.md](./references/headings-structure.md) | H1\u2013H6, outline do documento, acessibilidade, SEO |\n"
    "| Links e Imagens | [links-images.md](./references/links-images.md) | Links relativos, badges, estilo referência, imagens |\n"
    "| Blocos de Código | [code-blocks.md](./references/code-blocks.md) | Inline, cercado, realce de sintaxe, diff, código em listas |\n"
    "| Tabelas e Listas | [tables-lists.md](./references/tables-lists.md) | Listas ordenadas/não-ordenadas, tarefas GFM, tabelas complexas |\n"
    "| Recursos Avançados | [advanced-features.md](./references/advanced-features.md) | Citações, HTML, footnotes, Mermaid, front matter YAML |\n"
    "| Compatibilidade | [compatibility.md](./references/compatibility.md) | CommonMark vs GFM vs GitLab, gotchas por plataforma |\n"
    "\n"
    "Estas referências são carregadas just-in-time quando necessário.\n"
    "\n"
    "---\n"
    "\n"
    "## Quick Examples\n"
    "\n"
    "### README básico com badges e seções essenciais\n"
    + TB + "markdown\n"
    "# Meu Projeto\n"
    "\n"
    "[![Licença](https://img.shields.io/badge/licença-MIT-verde)](LICENSE)\n"
    "[![Versão](https://img.shields.io/badge/versão-1.0.0-azul)](CHANGELOG.md)\n"
    "\n"
    "Descrição breve do projeto em uma ou duas linhas.\n"
    "\n"
    "## Instalação\n"
    "\n"
    + TB + "bash\n"
    "pip install meu-projeto\n"
    + TB + "\n"
    "\n"
    "## Uso básico\n"
    "\n"
    + TB + "python\n"
    "from meu_projeto import principal\n"
    "principal()\n"
    + TB + "\n"
    + TB + "\n"
    "\n"
    "### Tabela de comparação com alinhamento misto\n"
    + TB + "markdown\n"
    "| Recurso          | CommonMark | GFM    | GitLab MD |\n"
    "|------------------|:----------:|:------:|:---------:|\n"
    "| Headings         | Sim        | Sim    | Sim       |\n"
    "| Tabelas          | Não        | Sim    | Sim       |\n"
    "| Task Lists       | Não        | Sim    | Sim       |\n"
    "| Mermaid          | Não        | Sim    | Sim       |\n"
    "| Footnotes        | Não        | Não    | Sim       |\n"
    + TB + "\n"
    "\n"
    "### Diagrama de sequência com Mermaid\n"
    + TB4 + "markdown\n"
    + TB + "mermaid\n"
    "sequenceDiagram\n"
    "    Cliente->>Servidor: Requisição GET /api/dados\n"
    "    Servidor->>Banco: SELECT * FROM dados\n"
    "    Banco-->>Servidor: Registros retornados\n"
    "    Servidor-->>Cliente: 200 OK + JSON\n"
    + TB + "\n"
    + TB4 + "\n"
    "\n"
    "Para exemplos detalhados, consulte as **[referências JIT](#referências-jit)**.\n"
    "\n"
    "---\n"
    "\n"
    "## Compatibility\n"
    "\n"
    "| CLI | Status | Notes |\n"
    "|-----|--------|---------|\n"
    "| Claude Code | Supported | Fully supported |\n"
    "| Gemini CLI | Supported | Fully supported |\n"
    "| OpenAI Codex | Supported | Fully supported |\n"
    "| GitHub Copilot | Supported | Fully supported |\n"
    "| OpenCode | Supported | Fully supported |\n"
    "| Cursor | Supported | Fully supported |\n"
    "| Qwen Code | Supported | Fully supported |\n"
    "\n"
    "**Requires:**\n"
    "- Acesso ao filesystem para ler e revisar documentos Markdown existentes\n"
    "- Conhecimento da plataforma de destino (GitHub, GitLab, docs sites)\n"
    "\n"
    "---\n"
    "\n"
    "## Segurança\n"
    "\n"
    "- Não executa código automaticamente\n"
    "- Não acessa rede ou recursos externos\n"
    "- Apenas leitura e análise/geração de texto Markdown\n"
    "- Sugestões seguem princípios de segurança: não inclui credenciais, tokens ou secrets em exemplos\n"
    "- Links externos em documentação devem ser verificados manualmente antes de publicar\n"
    "- Front matter YAML não deve conter dados sensíveis; use variáveis de ambiente quando necessário\n"
    "- Seções colapsáveis (`<details>`) não devem ser usadas para ocultar informações de segurança críticas\n"
    "\n"
    "---\n"
    "\n"
    "## Fontes\n"
    "\n"
    "| Fonte | Tipo | URL |\n"
    "|-------|------|-----|\n"
    "| CommonMark Spec | Especificação | [spec.commonmark.org](https://spec.commonmark.org/) |\n"
    "| GitHub Flavored Markdown | Oficial (GitHub) | [docs.github.com/en/get-started/writing-on-github](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github) |\n"
    "| GitLab Markdown | Oficial (GitLab) | [docs.gitlab.com/ee/user/markdown.html](https://docs.gitlab.com/ee/user/markdown.html) |\n"
    "| Mermaid JS Docs | Oficial (Mermaid) | [mermaid.js.org](https://mermaid.js.org/) |\n"
    "| W3C WCAG 2.1 | Padrão Acessibilidade | [w3.org/WAI/WCAG21/Overview](https://www.w3.org/WAI/WCAG21/Overview.html) |\n"
    "\n"
    "---\n"
    "\n"
    "**Version**: 1.0.0\n"
    "**Created**: 2026-02-05\n"
    "**License**: MIT\n"
)

lines = SKILL_MD.strip().split('\n')
print(f"SKILL.md: {len(lines)} lines")

outdir = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(outdir, '_SKILL.md'), 'w', encoding='utf-8') as f:
    f.write(SKILL_MD.strip() + '\n')

print("SKILL.md written OK")
